version: '2'

services:
  dynamodb:
    container_name: messenger_dynamodb
    image: cnadiminti/dynamodb-local
    restart: always
    volumes:
      - ./docker/db/dynamodb:/dynamodb_local_db
    ports:
      - 8000:8000
  sqs-local:
    container_name: messenger_sqs
    image:  roribio16/alpine-sqs
    restart: always
    ports:
      - 9324:9324
      - 9325:9325
    stdin_open: true
    tty: true
    volumes:
      - ./opt/sqs-conf:/opt/custom
  sns-local:
    container_name: messenger_sns
    image: s12v/sns
    environment:
      - DB_PATH=/docker/snsdb/db.json
    ports:
      - 9911:9911
