version: '2'

services:
  dynamodb:
    container_name: messenger_dynamodb
    image: cnadiminti/dynamodb-local
    restart: always
    volumes:
      - ./docker/db/dynamodb:/dynamodb_local_db
    ports:
      - 8000:8000
  sqs:
    image: s12v/elasticmq
    ports:
      - 9324:9324
    volumes:
      - ./config/elasticmq.conf:/etc/elasticmq/elasticmq.conf 
  sns-local:
    container_name: messenger_sns
    image: s12v/sns
    ports:
      - 9911:9911
    volumes:
      - ./config/db.json:/etc/sns/db.json
    depends_on:
      - sqs
  postgresql:
    container_name: messages_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_DB: edm_database
      POSTGRES_USER: edm_user
      POSTGRES_PASSWORD: edm@123
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
  adminer:
    image: adminer
    restart: always
    ports:
      - 8002:8080
